name: Snyk monitor dependencies

on: 
  push:
    branches:
    - next

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Run Snyk to monitor dependencies
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: monitor
        args: --org=iota-foundation
